name: Integrity check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    
    - name: Install PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: 8.0

    - name: Install composer deps
      run: |
        # Install app deps
        composer install --no-interaction --prefer-dist

    - name: Check PHPStan rules
      run: composer phpstan
